databases:
    el:
        host: "analytics-store.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: log
defaults:
    db: el
graphs: # removing this empty section makes generate.py crash

reportupdater-output: /a/limn-public-data/extdist/datafiles

reportupdater-reports:
    extension_downloads:
        frequency: days
        granularity: months
        timeboxed: true
        starts: 2015-07-01

    skin_downloads:
        frequency: days
        granularity: months
        timeboxed: true
        starts: 2015-07-01

    downloads:
        frequency: days
        granularity: months
        timeboxed: true
        starts: 2015-07-01
        funnel: true # enables multiple lines for the same date
